// <auto-generated />
using System;
using AuditApp.Data.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditApp.Data.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AuditApp.Data.Entities.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Audit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionType = "INSERT",
                            EntityId = 1,
                            EntityName = "Customer",
                            NewValues = "{\"id\":1, \"name\":\"asd\", \"cnp\":\"1234567812345\"}",
                            TimeStamp = new DateTime(2022, 8, 3, 7, 1, 31, 690, DateTimeKind.Utc).AddTicks(3000)
                        },
                        new
                        {
                            Id = 2,
                            ActionType = "DELETE",
                            EntityId = 1,
                            EntityName = "Customer",
                            OldValues = "{\"id\":1, \"name\":\"asd\", \"cnp\":\"1234567812345\"}",
                            TimeStamp = new DateTime(2022, 8, 3, 7, 1, 31, 690, DateTimeKind.Utc).AddTicks(3007)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
